### ISSUE TITLE
Wabbajack Enchantment causing Save Serializer to crash

### ISSUE THREAD

**Issue by morgannmccarty** [daleao/sdv-mods#5]
When the Wabbajack enchantment spawns monsters which should not exist in areas where they should not be (e.g. The Ridge in Ridgeside Valley) on saving the game the game will freeze on saving as they cannot be saved.

i.e. a mummy spawned in the Ridgeside Ridge and the game failed on saving.

### Relevent log:
 https://smapi.io/log/e05a18ec4e6649f8b74b029dbb466a8e

### Relevent issue for when log expires:

```console
InvalidOperationException: There was an error generating the XML document.
 ---> InvalidOperationException: The type StardewValley.Monsters.Mummy was not expected. Use the XmlInclude or SoapInclude attribute to specify types that are not known statically.
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterSaveGame.Write100_NPC(String n, String ns, NPC o, Boolean isNullable, Boolean needType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterSaveGame.Write188_GameLocation(String n, String ns, GameLocation o, Boolean isNullable, Boolean needType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterSaveGame.Write269_SaveGame(String n, String ns, SaveGame o, Boolean isNullable, Boolean needType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterSaveGame.Write270_SaveGame(Object o)
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlSerializer.Serialize(XmlWriter xmlWriter, Object o, XmlSerializerNamespaces namespaces, String encodingStyle, String id)
   at SpaceCore.Patches.SaveGamePatcher.SerializeProxy(XmlSerializer serializer, XmlWriter origWriter, Object obj) in C:\Programming\StardewValley\ModSource\SpaceCore\Patches\SaveGamePatcher.cs:line 401
   at StardewValley.SaveGame+<getSaveEnumerator>d__90.MoveNext_PatchedBy<spacechase0.SpaceCore>(<getSaveEnumerator>d__90 this)
   at StardewValley.SaveGame.<>c__DisplayClass88_0.<Save>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
```

### See: 
https://github.com/daleao/sdv-mods/blob/7f2ae764410f28cb9d89b3cad3299a4f58a90a9a/Modular%20Overhaul/Modules/Enchantments/Commands/WabbajackCommand.cs#L71
and
https://github.com/daleao/sdv-mods/blob/7f2ae764410f28cb9d89b3cad3299a4f58a90a9a/Modular%20Overhaul/Modules/Enchantments/Melee/WabbajackEnchantment.cs#L137

### Recommendation:
Either remove monsters from spawn list (entirely or) unless location in the Mines/Skull Cavern/(maybe) Farm, remove the Wabbajack enchantment entirely and rework, or add configuration option to remove the Wabbajack enchantment and set default to true to prevent potential issues.

(send me a message here or lillobby6 on Discord/[Nexus](https://www.nexusmods.com/users/48706303) and I can help with a PR if you want)

**Comment by daleao** [comment]
It sounds like your philosophy towards "feature doesn't work" is "remove feature", instead of "fix feature".
So "no thanks" on the PR, but thanks for pointing out the issue.

**Comment by morgannmccarty** [comment]
> It sounds like your philosophy towards "feature doesn't work" is "remove feature", instead of "fix feature".

Main reason I say that it should be reconsidered or more fittingly put under a config option is that in the current game cannot save monsters. As this is right now it will break with every expansion mod that adds new areas with monsters and do not consider that every monster could spawn there.

I don't believe it has to be removed, but a proper fix (for it to work universally) would require patches to be made by every mod attempting to work with this one. Alternatively you could check that the area is a vanilla area

I think the enchantments module is very interesting, but this is a serious bug which breaks a lot of things, additionally having a config option to enable/disable either just this enchantment or all enchantments modularly would vastly improve the customizability of the mod and help prevent additional incompatibility issues.

**Comment by daleao** [comment]
I understand the issue. My immediate thought was, if the monsters are causing save issues, then just remove those monsters before the game saves. No patches or config options needed.

**Comment by morgannmccarty** [comment]
Awesome! I'll give it a try and see if I can replicate the issue.

**Comment by morgannmccarty** [comment]
Had it reoccur with the "Leaper" this time (assuming this is the spider that can spawn from it from looking at decomp SDV)

[Log link](https://smapi.io/log/8bd9a0bde6bd4c349ce18e2fbba52cb0) - on MARGO 2.5.7

```console
 ---> InvalidOperationException: The type StardewValley.Monsters.Leaper was not expected. Use the XmlInclude or SoapInclude attribute to specify types that are not known statically.
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterSaveGame.Write100_NPC(String n, String ns, NPC o, Boolean isNullable, Boolean needType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterSaveGame.Write188_GameLocation(String n, String ns, GameLocation o, Boolean isNullable, Boolean needType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterSaveGame.Write269_SaveGame(String n, String ns, SaveGame o, Boolean isNullable, Boolean needType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterSaveGame.Write270_SaveGame(Object o)
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlSerializer.Serialize(XmlWriter xmlWriter, Object o, XmlSerializerNamespaces namespaces, String encodingStyle, String id)
   at SpaceCore.Patches.SaveGamePatcher.SerializeProxy(XmlSerializer serializer, XmlWriter origWriter, Object obj) in C:\Programming\StardewValley\ModSource\SpaceCore\Patches\SaveGamePatcher.cs:line 401
   at StardewValley.SaveGame+<getSaveEnumerator>d__90.MoveNext_PatchedBy<spacechase0.SpaceCore>(<getSaveEnumerator>d__90 this)
   at StardewValley.SaveGame.<>c__DisplayClass88_0.<Save>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
[SMAPI] An error occurred in the overridden update loop: InvalidOperationException: There was an error generating the XML document.
 ---> InvalidOperationException: The type StardewValley.Monsters.Leaper was not expected. Use the XmlInclude or SoapInclude attribute to specify types that are not known statically.
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterSaveGame.Write100_NPC(String n, String ns, NPC o, Boolean isNullable, Boolean needType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterSaveGame.Write188_GameLocation(String n, String ns, GameLocation o, Boolean isNullable, Boolean needType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterSaveGame.Write269_SaveGame(String n, String ns, SaveGame o, Boolean isNullable, Boolean needType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterSaveGame.Write270_SaveGame(Object o)
   --- End of inner exception stack trace ---
   at StardewValley.SaveGame.Save()+MoveNext() in stardewvalley\Farmer\Farmer\SaveGame.cs:line 416
   at StardewValley.Menus.SaveGameMenu.update_PatchedBy<spacechase0.SpaceCore>(SaveGameMenu this, GameTime time)
   at StardewValley.Game1._update(GameTime gameTime)
   at StardewValley.Game1.Update(GameTime gameTime)
   at StardewModdingAPI.Framework.SCore.OnPlayerInstanceUpdating(SGame instance, GameTime gameTime, Action runUpdate)
   ```
   
I'm not 100% sure what happened in this instance as I was trying to transfigure as many enemies as possible without killing them to try and retrigger the bug, but I had a spider get transfigured in the same location as before.

Part of me thought I accidentally killed the spider before so it might be necessary to recheck, but my current setup makes checking this particular error somewhat difficult. I can potentially check later on my modding setup (less mods and cheats so I can test it faster).
